### ISSUE TITLE
Feature Request - Additional Peer Information & Transaction/SmartContract Information

### ISSUE THREAD

**Issue by lukasosterheider** [ConsenSys/quorum-explorer#34]
Hey ConsenSys-Team!

Very happy to see that there is a new open source Quorum explorer coming.

A feature, I would look out for - as part of the PharmaLedger.eu project - is a more detailed information about peers and transaction.

Regarding peers - this would include a list of all peers inlcuding:
- enode information incl. inbound IP/DNS
- current block height
- external IP address (outbound IP address of the peer node)
- type - validator or member
- if validator, the validator key
- last connection timestamp

Regarding transaction - overviews similar to the Epirus explorer for transcations and smart contract transactions would be really nice.

Examples of a public epirus installation:
- Transactions: http://13.77.178.91/transactions
- Smart Contract Transactions: http://13.77.178.91/contracts/0x19fc9f98ab7675B98aA392f05121C8877fc74932

I am happy to join any discussion. Please let me know if you need more information and look forward to your feedback.

Best regards,
Lukas

**Comment by Ezzahhh** [comment]
Hi Lukas,

I think the addition of peer information could be a good feature to add to the explorer. We will see if an additional panel could be added to show peer list information calling the `admin_peers` or `admin.peers` APIs for Besu and GoQuorum.

It should be noted that the Quorum Explorer was built with the original purpose of only providing a cursory look into a private network. It is primarily used with the [quorum-dev-quickstart](https://github.com/ConsenSys/quorum-dev-quickstart) to demo public/private transactions and to allow new-comers into the blockchain space a visual interface to see their private network. For those reasons, I don't think a full block explorer like Epirus or Blockscout are within the scope of the Quorum Explorer, as this app was designed to be light enough to be run with the quickstart on a local machine, and building a full explorer would require a proper database and more considerations. 

Please let us know if you have any more questions or queries.

**Comment by Ezzahhh** [comment]
Some basic peer information has been merged into master, let me know what you think!

**Comment by lukasosterheider** [comment]
Thanks Eric!
This really helps us!
Additional information that would be cool are "last connection timestamp" and "current block height". I don't know if this is possible.

**Comment by Ezzahhh** [comment]
The last connection timestamp is not possible through the API that's available from the clients. The block height is currently shown for the particular node that is selected from the top-left drop-down so I think it is unnecessary to show this in the peer information for each node.

**Comment by lukasosterheider** [comment]
Alright 👍 
I just saw the block height as interesting in case of nodes have to re-sync / newly sync.

Another feature a colleague of mine just brought up a new idea:

- Is it possible to map the enode id (
enode://**%ENODE-ID%**@0.1.2.3:30303?discport=0) to specific names?
- We at Bayer have a network with some other companies. Therefore, it would be really nice to see to which other companies we are connected. We have a mapping of enode IDs to the company names and can provide this in JSON, CSV or similar available.
- It would be great if the mapping could be used to display the company names in the peer list. And maybe it could even say something link "No connection to companyA and companyB exists." if there is no connection to a mapped enode ID.

**Comment by joshuafernandes** [comment]
Hi @lukasosterheider, this functionality is a bit too specific and we'd like to keep this explorer generic to support a broader user base - I think the best way to proceed with that request is to make a fork and add the functionality that you require? Am closing this issue though, feel free to open a new issue for any new features
