### ISSUE TITLE
Not found contract after refresh

### ISSUE THREAD

**Issue by owyah** [ConsenSys/quorum-explorer#35]
I have been created custom smart contract inside Contract menu. When I refres the page, the deployed smart contract is not showing up. How to find existing/deployed smart contract?

**Comment by Ezzahhh** [comment]
Currently, the app will not save the contract addresses when you navigate off the page so each time you return to the contracts page you must redeploy the contracts to interact with them. I think adding support for interacting with an existing contract and saving the contract addresses after deployment is a good idea.

**Comment by joshuafernandes** [comment]
Closing inactive issue
