### ISSUE TITLE
Question: Can't compile smart contracts through quorum-explorer

### ISSUE THREAD

**Issue by rere61** [ConsenSys/quorum-explorer#67]
After following the "Quorum Developer Quickstart" tutorial on the GoQuorum website, when I attempt to compile built-in contracts (such as SimpleStorage) using Explorer, I encounter a Backend API Error: "Issue encountered from the back-end!"

There is a timeout error seen in DevTool, the error request url is as below:
http://oo.oo.oo.oo:25000/explorer/api/contractCompile

![2023-11-03 16 15 17](https://github.com/Consensys/quorum-explorer/assets/86316543/5c7bc7c5-a65a-4485-8c3c-b5f736ee2d85)

![2023-11-03 16 13 40](https://github.com/Consensys/quorum-explorer/assets/86316543/2406cc58-a271-43a8-9651-4cc6342fed4e)

**Comment by Wangouf** [comment]
Set the timeout longer,for example 50000.In src\common\components\Contracts\ContractsIndex.tsx, line331:
data: JSON.stringify({
        name: selectedContract,
        content: code,
        version: solidityVer,
      }),
      baseURL: `${publicRuntimeConfig.QE_BASEPATH}`,
      timeout: 50000,
    })
